# Generated by Django 5.0.1 on 2024-01-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.IntegerField(max_length=50)),
                ('port', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=100)),
                ('anonymity', models.CharField(max_length=100)),
                ('speed', models.FloatField(default=0)),
                ('uptime', models.FloatField(default=0)),
                ('last_check', models.CharField(max_length=100)),
                ('response', models.FloatField(default=0)),
                ('latency', models.FloatField(default=0)),
                ('org_and_asn', models.CharField(max_length=100)),
            ],
        ),
    ]
